import 'package:equatable/equatable.dart';
enum JournalMood { calm, reflective, productive, anxious }
extension JournalMoodX on JournalMood { String get label => switch (this) { JournalMood.calm => 'Calm', JournalMood.reflective => 'Reflective', JournalMood.productive => 'Productive', JournalMood.anxious => 'Anxious' }; String get emoji => switch (this) { JournalMood.calm => '☁️', JournalMood.reflective => '🌙', JournalMood.productive => '⚡', JournalMood.anxious => '🫧' }; }
class JournalModel extends Equatable { const JournalModel({required this.id, required this.title, required this.transcript, required this.createdAt, required this.mood, required this.duration, this.audioPath, this.isFavorite = false}); final String id; final String title; final String transcript; final DateTime createdAt; final JournalMood mood; final Duration duration; final String? audioPath; final bool isFavorite;
  bool get hasAudio => audioPath != null && audioPath!.isNotEmpty;
  JournalModel copyWith({bool? isFavorite}) => JournalModel(id: id, title: title, transcript: transcript, createdAt: createdAt, mood: mood, duration: duration, audioPath: audioPath, isFavorite: isFavorite ?? this.isFavorite);
  Map<String, dynamic> toMap() => {'id': id, 'title': title, 'transcript': transcript, 'createdAt': createdAt.toIso8601String(), 'mood': mood.name, 'durationMs': duration.inMilliseconds, 'audioPath': audioPath, 'isFavorite': isFavorite};
  factory JournalModel.fromMap(Map<dynamic, dynamic> map) => JournalModel(id: map['id'] as String, title: map['title'] as String, transcript: map['transcript'] as String? ?? '', createdAt: DateTime.parse(map['createdAt'] as String), mood: JournalMood.values.byName(map['mood'] as String), duration: Duration(milliseconds: map['durationMs'] as int), audioPath: map['audioPath'] as String?, isFavorite: map['isFavorite'] as bool? ?? false);
  @override List<Object?> get props => [id, title, transcript, createdAt, mood, duration, audioPath, isFavorite]; }
